### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by alain94** [ibrahimkarayel/todoBoot#1]
hello Ibrahim, I downloaded the application of GitHub and I modified the log directory, but when I exucute the app it shows me errors in java, so help me please :)﻿
![rbrggr](https://user-images.githubusercontent.com/39521226/40360092-34bcdd9c-5dc5-11e8-8239-97067909d86e.png)

**Comment by ibrahimkarayel** [comment]
Hello,
it looks like you cannot connect to MYSQL. Please check.

> `spring.datasource.url=jdbc:mysql://localhost:3306/tododb?createDatabaseIfNotExist=true&amp;amp;useUnicode=true&amp;amp;characterEncoding=utf-8&amp;amp;autoReconnect=true
spring.datasource.username=root
spring.datasource.password=root`
